export const FETCH_CRYPTOCURRENCYLIST_START = 'FETCH_CRYPTOCURRENCYLIST_START';
export const FETCH_CRYPTOCURRENCYLIST_SUCCESS =
  'FETCH_CRYPTOCURRENCYLIST_SUCCESS';
export const FETCH_CRYPTOCURRENCYLIST_FAILURE =
  'FETCH_CRYPTOCURRENCYLIST_FAILURE';
