export const FETCH_CRYPTOCURRENCYLIST_LOAD = 'FETCH_CRYPTOCURRENCYLIST_LOAD';
export const FETCH_CRYPTOCURRENCYLIST_SUCCESS =
  'FETCH_CRYPTOCURRENCYLIST_SUCCESS';
export const FETCH_CRYPTOCURRENCYLIST_FAILURE =
  'FETCH_CRYPTOCURRENCYLIST_FAILURE';
