export const FETCH_CURRENCIES_START = 'FETCH_CURRENCIES_START';
export const FETCH_CURRENCIES_SUCCESS = 'FETCH_CURRENCIES_SUCCESS';
export const FETCH_CURRENCIES_FAILURE = 'FETCH_CURRENCIES_FAILURE';

export const CURRENCY_CONVERT_START = 'CURRENCY_CONVERT_START';
export const CURRENCY_CONVERT_SUCCESS = 'CURRENCY_CONVERT_SUCCESS';
export const CURRENCY_CONVERT_FAILURE = 'CURRENCY_CONVERT_FAILURE';
